# =============================================================================
# Linear Integer Programming Model for Keyboard Production Optimization
#
# Five-Element Model Format:
#
# Objective:
#   Maximize total revenue from producing full-weighted (x) and semi-weighted (y) keyboards.
#
# Variables:
#   x: Number of full-weighted keyboards produced (integer, x >= 0)
#   y: Number of semi-weighted keyboards produced (integer, y >= 0)
#
# Constraints:
#   1) Oscillator chips: 20 * x + 15 * y <= 3500
#   2) Production time: 1.2 * x + 1.2 * y <= 6
#   3) Non-negativity and integrality: x, y >= 0 and integer
#
# Sets/Parameters:
#   All coefficients and right-hand sides are defined as Param objects.
#
# Additional Notes:
#   - All model coefficients and bounds are handled via Params.
#   - Variable bounds enforced with Params for Pyomo compliance.
#   - Model uses NonNegativeIntegers domain for x, y.
#   - The solution reports status, termination condition, optimal values, objective, and filename.
#   - Assumes an accessible integer-capable solver (e.g., 'glpk' or 'cbc') is available.
#   - ASCII only: no special Unicode used.
# =============================================================================

from pyomo.environ import ConcreteModel, Var, Objective, Constraint, Param, NonNegativeIntegers, maximize, SolverFactory, value

def solve_keyboard_lp():
    # ===== Model Definition =====
    model = ConcreteModel()

    # Parameters - objective coefficients
    model.price_full = Param(initialize=2800)
    model.price_semi = Param(initialize=2400)

    # Parameters - constraint coefficients
    model.chip_full = Param(initialize=20)   # chips needed per full-weighted
    model.chip_semi = Param(initialize=15)   # chips needed per semi-weighted
    model.chip_max = Param(initialize=3500)  # total chips available

    model.time_full = Param(initialize=1.2)
    model.time_semi = Param(initialize=1.2)
    model.time_max = Param(initialize=6)

    # Variable upper bounds based on chip constraints
    model.x_ub = Param(initialize=int(model.chip_max.value // model.chip_full.value))
    model.y_ub = Param(initialize=int(model.chip_max.value // model.chip_semi.value))

    # Decision variables (integer, nonnegative)
    model.x = Var(domain=NonNegativeIntegers, bounds=(0, model.x_ub.value))
    model.y = Var(domain=NonNegativeIntegers, bounds=(0, model.y_ub.value))

    # Objective: maximize revenue
    def revenue_rule(m):
        return m.price_full * m.x + m.price_semi * m.y
    model.objective = Objective(rule=revenue_rule, sense=maximize)

    # Constraints
    def chip_constraint_rule(m):
        return m.chip_full * m.x + m.chip_semi * m.y <= m.chip_max
    model.chip_constraint = Constraint(rule=chip_constraint_rule)

    def time_constraint_rule(m):
        return m.time_full * m.x + m.time_semi * m.y <= m.time_max
    model.time_constraint = Constraint(rule=time_constraint_rule)

    # ===== Solver Execution =====
    solver = None
    for candidate in ['cbc', 'glpk']:
        try:
            solver = SolverFactory(candidate)
            if solver.available():
                break
        except Exception:
            solver = None
    result_dict = {
        'status': None,
        'termination': None,
        'objective': None,
        'x_val': None,
        'y_val': None,
        'solver': None,
        'error': None
    }
    if solver is not None and solver.available():
        results = solver.solve(model)
        result_dict['status'] = results.solver.status
        result_dict['termination'] = results.solver.termination_condition
        result_dict['solver'] = solver.name
        if (str(results.solver.termination_condition).lower() in ['optimal', 'feasible']):
            result_dict['objective'] = value(model.objective)
            result_dict['x_val'] = value(model.x)
            result_dict['y_val'] = value(model.y)
    else:
        result_dict['error'] = 'No suitable solver (cbc or glpk) found. Please install a compatible MIP solver for Pyomo.'

    return result_dict

# File generated by algebraic_optimizer_agent for Keyboard LP task.
